<?php

declare(strict_types = 1);

namespace Omnipay\Cashu\Traits;

trait ParamsTrait
{
    /**
     * Get the payment currency code.
     *
     * @return string
     */
    public function getCurrency() : string
    {
        return (string) $this->getParameter('currency');
    }

    /**
     * Sets the payment currency code.
     *
     * @param string $value
     *
     * @return static
     */
    public function setCurrency($value) : static
    {
        return $this->setParameter('currency', strtolower($value));
    }

    /**
     * Get the amount
     *
     * @return string
     */
    public function getAmount() : string
    {
        return (string) $this->getParameter('amount');
    }

    /**
     * Sets the payment amount.
     *
     * @param string $value
     *
     * @return static
     */
    public function setAmount($value) : static
    {
        return $this->setParameter('amount', (string) $value);
    }

    /**
     * @return string
     */
    public function getLanguage() : string
    {
        return (string) $this->getParameter('language');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setLanguage(string $value) : static
    {
        return $this->setParameter('language', $value);
    }

    /**
     * Get the transaction ID.
     *
     * The transaction ID is the identifier generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId() : string
    {
        return (string) $this->getParameter('transactionId');
    }

    /**
     * Sets the transaction ID.
     *
     * @param string $value
     *
     * @return static
     */
    public function setTransactionId($value) : static
    {
        return $this->setParameter('transactionId', (string) $value);
    }

    /**
     * @return string
     */
    public function getTxt1() : string
    {
        return (string) $this->getParameter('txt1');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setTxt1(string $value) : static
    {
        return $this->setParameter('txt1', $value);
    }

    /**
     * @return string
     */
    public function getTxt2() : string
    {
        return (string) $this->getParameter('txt2');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setTxt2(string $value) : static
    {
        return $this->setParameter('txt2', $value);
    }

    /**
     * @return string
     */
    public function getTxt3() : string
    {
        return (string) $this->getParameter('txt3');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setTxt3(string $value) : static
    {
        return $this->setParameter('txt3', $value);
    }

    /**
     * @return string
     */
    public function getTxt4() : string
    {
        return (string) $this->getParameter('txt4');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setTxt4(string $value) : static
    {
        return $this->setParameter('txt4', $value);
    }

    /**
     * @return string
     */
    public function getTxt5() : string
    {
        return (string) $this->getParameter('txt5');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setTxt5(string $value) : static
    {
        return $this->setParameter('txt5', $value);
    }

    /**
     * @return string
     */
    public function getServiceName() : string
    {
        return (string) $this->getParameter('serviceName');
    }

    /**
     * @param string $value
     *
     * @return static
     */
    public function setServiceName(string $value) : static
    {
        return $this->setParameter('serviceName', $value);
    }
}
